---
# Can be accessed via ansible.builtin.apt - Manages apt-packages
- name: Set up EC2 Instances
  hosts: AnsibleKey # The Ansible key group name
  tasks:
    - name: Install Python3-pip
      apt:
        name: python3-pip
        state: 'present'
