name: Ansible Deployment

on:
  push:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  ansible-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.7

    - name: Cache Multiple Paths to Speedup Workflow Execution Time
      id: cache-step
      uses: actions/cache@v4.0.2
      with:
        path: |
          ~/cache/
          ~/.ansible/
        key: ${{ runner.os }}-ansible-${{ hashFiles('**/requirements.yml') }}-${{ github.sha }}
        # restore-keys: |
        #   ${{ runner.os }}-ansible-

    - name: Install Python 3.10 and pip
      run: |
        sudo apt-get update
        sudo apt-get install -y python3.10 python3-pip
        python3.10 -m pip install --upgrade pip

    - name: Install Ansible and Python Libraries (AWS SDKs)
      if: steps.cache-step.outputs.cache-hit != 'true'
      run: |
        python3.10 -m pip install ansible boto3 botocore

    - name: Install Ansible Galaxy Collection (amazon.aws)
      if: steps.cache-step.outputs.cache-hit != 'true'
      run: |
        ansible-galaxy collection install amazon.aws --force

    - name: Authenticate to AWS Using OpenID Connect
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::295793222430:role/github-actions-ansible-aws-oidc

    - name: Verify Ansible Python Interpreter
      id: verify-python-interpreter
      run: |
        ansible_python_interpreter=$(ansible -m setup localhost | grep '"ansible_python"' | awk -F '"' '{print $4}')
        echo "Ansible is using Python interpreter: $ansible_python_interpreter"
        echo "ANSIBLE_PYTHON_INTERPRETER=$ansible_python_interpreter" >> $GITHUB_ENV

    - name: Ensure boto3 and botocore are installed in Ansible Python environment
      run: |
        ansible_python_interpreter=$(ansible -m setup localhost | grep '"ansible_python"' | awk -F '"' '{print $4}')
        $ansible_python_interpreter -m pip install boto3 botocore

    - name: Debug:List Files for Verification
      run: |
        ls -l
        ls -l ~/cache
        ls -l ~/.ansible
        cat my_inventory.aws_ec2.yml  # Check if the inventory file is accessible and in the correct format

    - name: Run Ansible Inventory Command
      env:
        ANSIBLE_PYTHON_INTERPRETER: ${{ steps.verify-python-interpreter.outputs.ANSIBLE_PYTHON_INTERPRETER }}
      shell: pwsh
      run: |
        ansible-inventory --inventory my_inventory.aws_ec2.yml --list
