name: Ansible Deployment

on:
  push:
  workflow_dispatch:

env:
  ANSIBLE_HOST_KEY_CHECKING: false
  ANSIBLE_REMOTE_USER: ubuntu

permissions:
  id-token: write
  contents: read

jobs:
  ansible-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.7

    - name: Cache Multiple Paths to Speedup Workflow Execution Time
      id: cache-step
      uses: actions/cache@v4.0.2
      with:
        path: |
          ~/
          ~/.ansible/
        key: ${{ runner.os }}-ansible-${{ hashFiles('**/requirements.yml') }}-${{ github.sha }}

    - name: Install Ansible and Python Libraries (AWS SDKs)
      if: steps.cache-step.outputs.cache-hit != 'true'
      run: |
        pip3 install ansible boto3 botocore

    - name: Install Ansible Galaxy Collection (amazon.aws)
      if: steps.cache-step.outputs.cache-hit != 'true'
      run: |
        ansible-galaxy collection install amazon.aws --force

    - name: Authenticate to AWS Using OpenID Connect
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::295793222430:role/github-actions-ansible-aws-oidc

    - name: Debug:List Files for Verification
      run: |
        ls -l
        ls -l ~/ || echo "Cache directory not found"
        ls -l ~/.ansible/
        cat my_inventory.aws_ec2.yml  # Check if the inventory file is accessible and in the correct format

    - name: Run Ansible Inventory Command
      run: |
        ansible-inventory --inventory my_inventory.aws_ec2.yml --list

    - name: Write SSH key to file
      run: |
        Set-Content -Path sshkeyfile -Value "${{ secrets.ANSIBLE_SSH_KEY }}"
        chmod 400 sshkeyfile
      # echo "${{ secrets.ANSIBLE_SSH_KEY }}" > sshkeyfile

    - name: Add SSH Key to Agent
      run: |
        eval "$(ssh-agent -s)"
        ssh-add sshkeyfile

    - name: Debug:Verify SSH Connectivity
      run: |
        ssh -v -i sshkeyfile -o StrictHostKeyChecking=no ec2-54-234-26-80.compute-1.amazonaws.com 'echo "SSH connection established"'

    - name: Run Ansible Playbook
      run: |
        ansible-playbook --inventory my_inventory.aws_ec2.yml --private-key sshkeyfile ansible-playbook.yml
