name: Ansible Deployment

on:
  push:
  workflow_dispatch:

jobs:
  ansible-deploy:
    runs-on: ubuntu-latest
    steps:
    - run: echo test
    - name: Authenticate to AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        audience: sts.amazonaws.com
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
